gateways:
  local:
    connection:
      type: motherduck
      database: wallets
      token: {{ env_var('MD_TOKEN') }}

default_gateway: local

model_defaults:
  dialect: duckdb
  start: 2024-12-15
