name: manual run pipelines

on:
  workflow_dispatch:

env:
  SOURCES__DUNE__API_KEY: ${{ secrets.SOURCES__DUNE__API_KEY }}
  SOURCES__DEBANK__ACCESS_KEY: ${{ secrets.SOURCES__DEBANK__ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: install poetry and run pipelines
        run: |
          pip install poetry
          poetry install
          cd pipelines && poetry run python main.py
